version: '3,8'

services:
  postgres:
    image: postgres:15
    container_name: fraudshield-db
    environment:
      POSTGRES_DB: fraudshield
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fraudshield-network

  redis:
    image: redis:7-alpine
    container_name: fraudshield-cache
    ports:
      - "6379:6379"
    networks:
      - fraudshield-network

volumes:
  postgres_data:

networks:
  fraudshield-network:
    driver: bridge